const types = {

  FETCH_EVENTS: 'FETCH_EVENTS',
  FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',

  FETCH_TREES: 'FETCH_TREES',
  FETCH_TREES_SUCCESS: 'FETCH_TREES_SUCCESS',
};

export default types;
