platform :ios, ’9.0’
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 

target ‘Platimi’ do
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'Alamofire', '~> 4.4'
    pod 'SwiftyJSON'
    pod 'SocketRocket'
    pod 'Gifu'
    pod 'PureLayout'
end


